# Generated by Django 4.1.2 on 2022-10-18 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Darbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=50, verbose_name='Pavadinimas')),
                ('pastabos', models.CharField(max_length=100, verbose_name='Pastabos')),
            ],
            options={
                'verbose_name': 'Darbas',
                'verbose_name_plural': 'Darbai',
            },
        ),
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=50, verbose_name='Vardas')),
                ('pavarde', models.CharField(max_length=50, verbose_name='Pavardė')),
                ('pareigos', models.CharField(max_length=50, verbose_name='Pareigos')),
            ],
            options={
                'verbose_name': 'Darbuotojas',
                'verbose_name_plural': 'Darbuotojai',
            },
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=50, verbose_name='Vardas')),
                ('pavarde', models.CharField(max_length=50, verbose_name='Pavardė')),
                ('imone', models.CharField(max_length=50, verbose_name='Įmonė')),
                ('tel_nr', models.IntegerField(verbose_name='Telefono numeris')),
                ('el_pastas', models.CharField(max_length=50, verbose_name='El. paštas')),
            ],
            options={
                'verbose_name': 'Klientas',
                'verbose_name_plural': 'Klientai',
            },
        ),
        migrations.CreateModel(
            name='Saskaita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('israsymo_data', models.DateField(auto_now_add=True, verbose_name='Išrašymo data')),
                ('suma', models.FloatField(max_length=10, verbose_name='Suma')),
            ],
            options={
                'verbose_name': 'Sąskaita',
                'verbose_name_plural': 'Sąskaitos',
            },
        ),
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=50, verbose_name='Pavadinimas')),
                ('pradzios_data', models.CharField(max_length=20, verbose_name='Pradžios data')),
                ('pabaigos_data', models.CharField(max_length=20, verbose_name='Pabaigos data')),
                ('atsakingasis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('darbai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.darbas')),
                ('darbuotojai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.darbuotojas')),
                ('klientas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.klientas')),
                ('saskaitos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.saskaita')),
            ],
            options={
                'verbose_name': 'Projektas',
                'verbose_name_plural': 'Projektai',
            },
        ),
    ]
