# Generated by Django 4.1.2 on 2022-10-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0002_saskaita_darbas_alter_projektas_pabaigos_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projektas',
            name='darbai',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='darbuotojai',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='saskaitos',
        ),
        migrations.RemoveField(
            model_name='saskaita',
            name='darbas',
        ),
        migrations.AddField(
            model_name='projektas',
            name='darbai',
            field=models.ManyToManyField(to='projektai.darbas'),
        ),
        migrations.AddField(
            model_name='projektas',
            name='darbuotojai',
            field=models.ManyToManyField(to='projektai.darbuotojas'),
        ),
        migrations.AddField(
            model_name='projektas',
            name='saskaitos',
            field=models.ManyToManyField(to='projektai.saskaita'),
        ),
        migrations.AddField(
            model_name='saskaita',
            name='darbas',
            field=models.ManyToManyField(to='projektai.darbas'),
        ),
    ]
