# Generated by Django 4.1.2 on 2022-10-18 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0003_remove_projektas_darbai_remove_projektas_darbuotojai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projektas',
            name='darbai',
        ),
        migrations.AddField(
            model_name='projektas',
            name='darbai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.darbas'),
        ),
    ]
