# Generated by Django 4.1.2 on 2022-10-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0004_remove_projektas_darbai_projektas_darbai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projektas',
            name='darbai',
        ),
        migrations.AddField(
            model_name='projektas',
            name='darbai',
            field=models.ManyToManyField(to='projektai.darbas'),
        ),
    ]
