# Generated by Django 4.1.2 on 2022-10-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0005_remove_projektas_darbai_projektas_darbai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darbas',
            name='pastabos',
            field=models.TextField(max_length=100, verbose_name='Pastabos'),
        ),
        migrations.AlterField(
            model_name='klientas',
            name='tel_nr',
            field=models.CharField(max_length=20, verbose_name='Telefono numeris'),
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='saskaitos',
        ),
        migrations.AddField(
            model_name='projektas',
            name='saskaitos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.saskaita'),
        ),
    ]
