# Generated by Django 4.1.2 on 2022-10-19 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0006_alter_darbas_pastabos_alter_klientas_tel_nr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saskaita',
            name='darbas',
        ),
        migrations.AddField(
            model_name='saskaita',
            name='darbas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.darbas'),
        ),
    ]
