# Generated by Django 4.1.2 on 2022-10-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0007_remove_saskaita_darbas_saskaita_darbas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saskaita',
            name='darbas',
        ),
    ]
