# Generated by Django 4.1.2 on 2022-10-22 20:14

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0008_remove_saskaita_darbas'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektas',
            name='aprasymas',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now, verbose_name='Tekstas'),
            preserve_default=False,
        ),
    ]
