# Generated by Django 4.1.2 on 2022-10-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0009_projektas_aprasymas'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektas',
            name='nuotrauka',
            field=models.ImageField(null=True, upload_to='nuotraukos', verbose_name='Nuotrauka'),
        ),
    ]
